package Bienes;

public class Bien{

	private String altaBien;

	public void setBien(String claseID, String claseName, String claseDescription, String subClaseID, String subClaseName, 
			String subClaseDescription, String marcaID, String marcaName, String marcaDescription, String modeloID, 
			String modeloName, String modeloDescription){

		this.altaBien=("{"+
				"\"classId\":" + claseID + ","+
				"\"className\":\"" + claseName + "\"," +
				"\"classDescription\":\"" + claseDescription + "\"," +
				"\"subclassId\":" + subClaseID + ","+
				"\"subclassName\":\"" + subClaseName + "\","+
				"\"subclassDescription\":\"" + subClaseDescription + "\","+
				"\"brandId\":" + marcaID + ","+
				"\"brandName\":\"" + marcaName + "\","+
				"\"brandDescription\":\"" + marcaDescription + "\","+
				"\"modelId\":" + modeloID + ","+
				"\"modelName\":\"" + modeloName + "\","+
				"\"modelDescription\":\"" + modeloDescription + "\","+
				"\"version\":\"Infoauto:FordFiestaKDTitanium5puertas1.6\","+
				"\"attributes\":["+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":1,"+
				"\"name\":\"Tipificación\","+
				"\"description\":\"Tipificación\","+
				"\"attributeValueType\":{"+
				"\"id\":4,"+
				"\"description\":\"Tabla\","+
				"\"code\":\"TABLA\""+
				"},"+
				"\"attributeFormat\":null,"+
				"\"status\":true,"+
				"\"options\":["+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Aerodinosengeneral(aviones,hidroaviones,helicópteros)\","+
				"\"uid\":1,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Aguadasybebederos\","+
				"\"uid\":2,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Alambradasytranqueras\","+
				"\"uid\":3,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Barcos\","+
				"\"uid\":4,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Contenedores(incluídoscontenedorescisternasycontenedoresdepósitosparacualquiermediodetransporte)\","+
				"\"uid\":5,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Contenedores,exceptosilos(toneles,tambores)\","+
				"\"uid\":6,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Cosechadoras(granos,oleaginosasyforrajes)\","+
				"\"uid\":7,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Edificios\","+
				"\"uid\":8,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Embarcacionesderecreo\","+
				"\"uid\":9,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equiposdecomputaciónyaccesoriosdeinformática\","+
				"\"uid\":10,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equiposymaquinariasdearrastre(sembradoras,discos,aradosdereja,aradosdecinceles,escardadores,etc)\","+
				"\"uid\":11,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equipos,aparatoseinstrumentaldeprecisióndeusotécnicoyprofesional\","+
				"\"uid\":12,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equipos,aparatoseinstrumentaldeusotécnicoyprofesional\","+
				"\"uid\":13,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Ferrocarriles(locomotorasyvagones)\","+
				"\"uid\":14,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Galpones\","+
				"\"uid\":15,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Haciendareproductora\","+
				"\"uid\":16,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Herramientas\","+
				"\"uid\":17,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Instalaciones\","+
				"\"uid\":18,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Maquinariasyequipos\","+
				"\"uid\":19,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Molinos\","+
				"\"uid\":20,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Mueblesyutiles\","+
				"\"uid\":21,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Pulverizadorasmotopropulsadas\","+
				"\"uid\":22,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Rodados(automóviles,camiones,acoplados,autoelevadores,grúas,máquinasvialesymotocicletas)\","+
				"\"uid\":23,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Rotoenfardadoras\","+
				"\"uid\":24,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Silos\","+
				"\"uid\":25,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Tarrostambo\","+
				"\"uid\":26,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Tractores\","+
				"\"uid\":27,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Software\","+
				"\"uid\":28,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"}"+
				"],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":true,"+
				"\"level\":2,"+
				"\"entity\":{"+
				"\"idEntity\":1,"+
				"\"name\":\"Tipificación\","+
				"\"entityTableName\":\"t_com_equipmentClassification\","+
				"\"entityCode\":\"description\","+
				"\"entityId\":\"idEquipmentClassification\""+
				"},"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":false,"+
				"\"idAttribute\":1,"+
				"\"idTableValue\":23,"+
				"\"optionValue\":null,"+
				"\"modificable\":false,"+
				"\"defineVersion\":false,"+
				"\"versionOrder\":0,"+
				"\"textValue\":\"\""+
				"},"+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":2,"+
				"\"name\":\"Patentable\","+
				"\"description\":\"SI/NO\","+
				"\"attributeValueType\":{"+
				"\"id\":3,"+
				"\"description\":\"Si/No\","+
				"\"code\":\"BOOLEAN\""+
				"},"+
				"\"attributeFormat\":null,"+
				"\"status\":true,"+
				"\"options\":[],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":true,"+
				"\"level\":2,"+
				"\"entity\":null,"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":true,"+
				"\"idAttribute\":2,"+
				"\"idTableValue\":null,"+
				"\"optionValue\":null,"+
				"\"modificable\":false,"+
				"\"defineVersion\":false,"+
				"\"versionOrder\":0,"+
				"\"textValue\":\"\""+
				"},"+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":3,"+
				"\"name\":\"Semaforo\","+
				"\"description\":\"SI/NO(Rojo/Verde)cuandoestáenSIimplicaquealcotizarestebiendebepasarporlasupervisióndeactivos\","+
				"\"attributeValueType\":{"+
				"\"id\":3,"+
				"\"description\":\"Si/No\","+
				"\"code\":\"BOOLEAN\""+
				"},"+
				"\"attributeFormat\":null,"+
				"\"status\":true,"+
				"\"options\":[],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":true,"+
				"\"level\":2,"+
				"\"entity\":null,"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":false,"+
				"\"idAttribute\":3,"+
				"\"idTableValue\":null,"+
				"\"optionValue\":null,"+
				"\"modificable\":false,"+
				"\"defineVersion\":false,"+
				"\"versionOrder\":0,"+
				"\"textValue\":\"\""+
				"},"+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":4,"+
				"\"name\":\"IVA%\","+
				"\"description\":\"PorcentajeIVA%\","+
				"\"attributeValueType\":{"+
				"\"id\":1,"+
				"\"description\":\"Texto\","+
				"\"code\":\"TEXTO\""+
				"},"+
				"\"attributeFormat\":{"+
				"\"id\":4,"+
				"\"description\":\"Decimal\","+
				"\"code\":\"DECIMAL\""+
				"},"+
				"\"status\":true,"+
				"\"options\":[],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":true,"+
				"\"level\":2,"+
				"\"entity\":null,"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":false,"+
				"\"idAttribute\":4,"+
				"\"idTableValue\":null,"+
				"\"optionValue\":null,"+
				"\"modificable\":false,"+
				"\"defineVersion\":false,"+
				"\"versionOrder\":0,"+
				"\"textValue\":\"21\""+
				"},"+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":301,"+
				"\"name\":\"Tipodeseguro\","+
				"\"description\":\"descripciontiposeguro\","+
				"\"attributeValueType\":{"+
				"\"id\":4,"+
				"\"description\":\"Tabla\","+
				"\"code\":\"TABLA\""+
				"},"+
				"\"attributeFormat\":null,"+
				"\"status\":true,"+
				"\"options\":["+
				"{"+
				"\"id\":null,"+
				"\"name\":\"AUTOMOTOR\","+
				"\"uid\":1,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"INGENIERIA\","+
				"\"uid\":2,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"AERONAUTICO\","+
				"\"uid\":3,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"}"+
				"],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":false,"+
				"\"level\":0,"+
				"\"entity\":{"+
				"\"idEntity\":3,"+
				"\"name\":\"InsuranceType\","+
				"\"entityTableName\":\"t_fin_InsuranceType\","+
				"\"entityCode\":\"InsuranceType_Name\","+
				"\"entityId\":\"InsuranceType_ID\""+
				"},"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":false,"+
				"\"idAttribute\":301,"+
				"\"idTableValue\":1,"+
				"\"optionValue\":null,"+
				"\"modificable\":false,"+
				"\"defineVersion\":false,"+
				"\"versionOrder\":0,"+
				"\"textValue\":\"\""+
				"},"+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":302,"+
				"\"name\":\"Claseseguro\","+
				"\"description\":\"descclaseseguro\","+
				"\"attributeValueType\":{"+
				"\"id\":4,"+
				"\"description\":\"Tabla\","+
				"\"code\":\"TABLA\""+
				"},"+
				"\"attributeFormat\":null,"+
				"\"status\":true,"+
				"\"options\":["+
				"{"+
				"\"id\":null,"+
				"\"name\":\"ACOPLADO\","+
				"\"uid\":1,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"AUTOGRUA\","+
				"\"uid\":2,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"AUTOMOVIL\","+
				"\"uid\":3,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"CAMIONHASTA4TN\","+
				"\"uid\":4,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"CAMIONMAS4TN\","+
				"\"uid\":5,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"PICKUPA\","+
				"\"uid\":6,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"PICKUPB\","+
				"\"uid\":7,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"COMUNICACIONESA1\","+
				"\"uid\":8,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"CONTRATISTAA1\","+
				"\"uid\":9,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"ELECTRONICOSA1\","+
				"\"uid\":10,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"MAQUINARIASA1\","+
				"\"uid\":11,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"MEDICOSA1\","+
				"\"uid\":12,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"MUEBLESA1\","+
				"\"uid\":13,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"SOFTWARE\","+
				"\"uid\":14,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"NOASEGURABLE\","+
				"\"uid\":15,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"CAMIONMAS4TNACCESORIOS\","+
				"\"uid\":16,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"ACOPLADOACCESORIOS\","+
				"\"uid\":17,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"AUTOMOVILACCESORIOS\","+
				"\"uid\":18,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"CAMIONHASTA4TNACCESORIOS\","+
				"\"uid\":19,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"PICKUPBACCESORIOS\","+
				"\"uid\":20,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"AERONAVES\","+
				"\"uid\":21,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"GR700EX\","+
				"\"uid\":22,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"PICKUPAACCESORIOS\","+
				"\"uid\":23,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"}"+
				"],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":false,"+
				"\"level\":0,"+
				"\"entity\":{"+
				"\"idEntity\":4,"+
				"\"name\":\"InsuranceClass\","+
				"\"entityTableName\":\"t_fin_InsuranceClass\","+
				"\"entityCode\":\"InsuranceClass_Name\","+
				"\"entityId\":\"InsuranceClass_ID\""+
				"},"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":false,"+
				"\"idAttribute\":302,"+
				"\"idTableValue\":3,"+
				"\"optionValue\":null,"+
				"\"modificable\":false,"+
				"\"defineVersion\":false,"+
				"\"versionOrder\":0,"+
				"\"textValue\":\"\""+
				"},"+
				"{"+
				"\"active\":false,"+
				"\"attribute\":{"+
				"\"id\":300,"+
				"\"name\":\"Infoauto\","+
				"\"description\":\"descripcioninfoauto\","+
				"\"attributeValueType\":{"+
				"\"id\":1,"+
				"\"description\":\"Texto\","+
				"\"code\":\"TEXTO\""+
				"},"+
				"\"attributeFormat\":{"+
				"\"id\":2,"+
				"\"description\":\"Alfanumérico\","+
				"\"code\":\"ALFANUMERICO\""+
				"},"+
				"\"status\":true,"+
				"\"options\":["+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Aerodinosengeneral(aviones,hidroaviones,helicópteros)\","+
				"\"uid\":1,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Aguadasybebederos\","+
				"\"uid\":2,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Alambradasytranqueras\","+
				"\"uid\":3,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Barcos\","+
				"\"uid\":4,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Contenedores(incluídoscontenedorescisternasycontenedoresdepósitosparacualquiermediodetransporte)\","+
				"\"uid\":5,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Contenedores,exceptosilos(toneles,tambores)\","+
				"\"uid\":6,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Cosechadoras(granos,oleaginosasyforrajes)\","+
				"\"uid\":7,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Edificios\","+
				"\"uid\":8,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Embarcacionesderecreo\","+
				"\"uid\":9,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equiposdecomputaciónyaccesoriosdeinformática\","+
				"\"uid\":10,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equiposymaquinariasdearrastre(sembradoras,discos,aradosdereja,aradosdecinceles,escardadores,etc)\","+
				"\"uid\":11,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equipos,aparatoseinstrumentaldeprecisióndeusotécnicoyprofesional\","+
				"\"uid\":12,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Equipos,aparatoseinstrumentaldeusotécnicoyprofesional\","+
				"\"uid\":13,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Ferrocarriles(locomotorasyvagones)\","+
				"\"uid\":14,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Galpones\","+
				"\"uid\":15,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Haciendareproductora\","+
				"\"uid\":16,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Herramientas\","+
				"\"uid\":17,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Instalaciones\","+
				"\"uid\":18,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Maquinariasyequipos\","+
				"\"uid\":19,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Molinos\","+
				"\"uid\":20,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Mueblesyutiles\","+
				"\"uid\":21,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Pulverizadorasmotopropulsadas\","+
				"\"uid\":22,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Rodados(automóviles,camiones,acoplados,autoelevadores,grúas,máquinasvialesymotocicletas)\","+
				"\"uid\":23,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Rotoenfardadoras\","+
				"\"uid\":24,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Silos\","+
				"\"uid\":25,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Tarrostambo\","+
				"\"uid\":26,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Tractores\","+
				"\"uid\":27,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"},"+
				"{"+
				"\"id\":null,"+
				"\"name\":\"Software\","+
				"\"uid\":28,"+
				"\"description\":null,"+
				"\"attributeDTO\":null"+
				"}"+
				"],"+
				"\"applyAsset\":false,"+
				"\"systemAttribute\":false,"+
				"\"level\":0,"+
				"\"entity\":{"+
				"\"idEntity\":1,"+
				"\"name\":\"Tipificación\","+
				"\"entityTableName\":\"t_com_equipmentClassification\","+
				"\"entityCode\":\"description\","+
				"\"entityId\":\"idEquipmentClassification\""+
				"},"+
				"\"key\":null"+
				"},"+
				"\"booleanValue\":false,"+
				"\"idAttribute\":300,"+
				"\"idTableValue\":null,"+
				"\"optionValue\":null,"+
				"\"modificable\":true,"+
				"\"defineVersion\":true,"+
				"\"versionOrder\":1,"+
				"\"textValue\":\"Versión 2.0\""+
				"}"+
				"]"+
				"}");
	}

	public String getBien(){
		return altaBien;
	}
}
